source :rubygems

group :development do
  gem 'meta_wordpress', :git    => '~/Projects/gems/meta_wordpress'
  gem 'guard-haml',     :git    => 'git://github.com/polarblau/guard-haml.git',
                        :branch => 'extensions'
  gem 'guard-sass'
  gem 'guard-coffee'
end
