require 'meta_wordpress'

guard 'coffeescript',
      :input  => 'javascripts/source',
      :output => 'javascripts/compiled'

guard 'haml',
      :haml_options => { :escape_attrs => false },
      :input => 'views' do
        watch %r{^views/.+(\.haml)?}
      end

guard 'sass',
      :input  => 'stylesheets/source',
      :output => 'stylesheets/compiled'
