require 'meta_wordpress'

guard 'coffeescript',
      :all_on_start => true,
      :input        => 'javascripts/source',
      :output       => 'javascripts/compiled'

guard 'haml',
      :haml_options => { :escape_attrs => false },
      :run_at_start => true,
      :input        => 'views' do
        watch %r{^views/.+(\.haml)?}
      end

guard 'sass',
      :all_on_start => true,
      :input        => 'stylesheets/source',
      :output       => 'stylesheets/compiled'
